"""initial layer A + vector extension

Revision ID: 52513f0eb85d
Revises: 
Create Date: 2026-06-17 20:04:18.416571
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52513f0eb85d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector：Layer C（P3）的向量欄位需要此 extension，於首個 migration 建立。
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('daily_runs',
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('high', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('low', sa.Integer(), nullable=False),
    sa.Column('urgent', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('budget_sum_wan', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('report_file', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('run_date', 'source_id')
    )
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('case_pk', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('org', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=8), nullable=True),
    sa.Column('budget_wan', sa.Integer(), nullable=True),
    sa.Column('deadline_roc', sa.String(length=16), nullable=True),
    sa.Column('deadline_iso', sa.Date(), nullable=True),
    sa.Column('tender_method', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=16), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'case_pk', name='uq_tender_source_case')
    )
    op.create_index(op.f('ix_tenders_case_pk'), 'tenders', ['case_pk'], unique=False)
    op.create_index(op.f('ix_tenders_city'), 'tenders', ['city'], unique=False)
    op.create_index(op.f('ix_tenders_deadline_iso'), 'tenders', ['deadline_iso'], unique=False)
    op.create_index(op.f('ix_tenders_last_seen'), 'tenders', ['last_seen'], unique=False)
    op.create_index(op.f('ix_tenders_source_id'), 'tenders', ['source_id'], unique=False)
    op.create_table('daily_tender',
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=8), nullable=True),
    sa.Column('days_left', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('run_date', 'tender_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_tender')
    op.drop_index(op.f('ix_tenders_source_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_last_seen'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_deadline_iso'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_city'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_case_pk'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_table('daily_runs')
    op.drop_table('sources')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
