"""add_tender_annotations_jsonb

Revision ID: 957639bef8a7
Revises: e9c1a4b7f3d2
Create Date: 2026-06-19 13:49:33.155972
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '957639bef8a7'
down_revision: Union[str, None] = 'e9c1a4b7f3d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'annotations')
    # ### end Alembic commands ###
