"""P4: layer_c_keyword_and_decision_vectors

Revision ID: ef13668b507f
Revises: 9a3f1c7d2b84
Create Date: 2026-06-18 15:01:10.952456
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# bge-m3 向量維度；與 app.models.knowledge.EMBED_DIM 一致。
EMBED_DIM = 1024

# revision identifiers, used by Alembic.
revision: str = 'ef13668b507f'
down_revision: Union[str, None] = '9a3f1c7d2b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_weights',
    sa.Column('term', sa.String(length=128), nullable=False),
    sa.Column('polarity', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('support', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('term')
    )
    op.create_index(op.f('ix_keyword_weights_polarity'), 'keyword_weights', ['polarity'], unique=False)
    op.create_index(op.f('ix_keyword_weights_updated_at'), 'keyword_weights', ['updated_at'], unique=False)
    op.create_table('doc_summaries',
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_terms', sa.Text(), nullable=True),
    sa.Column('source_doc_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tender_id')
    )
    op.create_table('decision_vectors',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('feasible', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_index('ix_decision_vectors_embedding_hnsw', 'decision_vectors', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_decision_vectors_tender_id'), 'decision_vectors', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_vectors_tender_id'), table_name='decision_vectors')
    op.drop_index('ix_decision_vectors_embedding_hnsw', table_name='decision_vectors', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('decision_vectors')
    op.drop_table('doc_summaries')
    op.drop_index(op.f('ix_keyword_weights_updated_at'), table_name='keyword_weights')
    op.drop_index(op.f('ix_keyword_weights_polarity'), table_name='keyword_weights')
    op.drop_table('keyword_weights')
    # ### end Alembic commands ###
